=== Clark1216/CE2M_Journey-TheWorldAvatar/JPS_Arbitrage/MoDS/HDMR_0%2E01_001/Working_dir/MoDS_inputs.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://como.cheng.cam.ac.uk/MoDS" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://como.cheng.cam.ac.uk/MoDS" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:complexType name="details">
    <xs:sequence>
      <xs:element maxOccurs="unbounded" name="detail">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:string">
              <xs:attribute name="name" type="xs:string" use="required" />
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="versionString">
  <xs:restriction base="xs:string">
    <xs:pattern value="([0-9]*\.?){3}(-.*)?"/>
  </xs:restriction>
</xs:simpleType>

  <xs:element name="mods">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="algorithms">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="algorithm">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="details" type="details" />
                  </xs:sequence>
                  <xs:attribute name="name" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="cases">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="case">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="details" type="details" />
                  </xs:sequence>
                  <xs:attribute name="name" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="files">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="file">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="details" type="details" />
                  </xs:sequence>
                  <xs:attribute name="file_name" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="functions" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="function">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="details" type="details" />
                  </xs:sequence>
                  <xs:attribute name="name" type="xs:string" use="required" />
                  <xs:attribute name="usage" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="parameters">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="parameter">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" name="scaling" type="xs:string" />
                    <xs:element name="cases">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="unbounded" name="case" type="xs:string" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="files">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element minOccurs="0" name="initial_read">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="details" type="details" />
                              </xs:sequence>
                              <xs:attribute name="file_name" type="xs:string" use="optional" />
                            </xs:complexType>
                          </xs:element>
                          <xs:element minOccurs="0" name="working_read">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="details" type="details" />
                              </xs:sequence>
                              <xs:attribute name="file_name" type="xs:string" use="optional" />
                            </xs:complexType>
                          </xs:element>
                          <xs:element minOccurs="0" name="working_write">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="details" type="details" />
                              </xs:sequence>
                              <xs:attribute name="file_name" type="xs:string" use="optional" />
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="type" type="xs:string" use="required" />
                  <xs:attribute name="subtype" type="xs:string" use="required" />
                  <xs:attribute name="case_detail_sep" type="xs:string" use="optional" />
                  <xs:attribute name="detail_sep" type="xs:string" use="optional" />
                  <xs:attribute name="n_params_per_case" type="xs:string" use="optional" />
                  <xs:attribute name="name" type="xs:string" use="optional" />
                  <xs:attribute name="name_suffix_detail" type="xs:string" use="optional" />
                  <xs:attribute name="preserve_white_space" type="xs:string" use="optional" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="version" type="versionString" use="optional" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Clark1216/CE2M_Journey-TheWorldAvatar/Agents/MoDSSimpleAgent/mods-simple-agent/src/main/resources/MoDS_inputs_templates/MOO.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<mods xsi:schemaLocation="http://como.cheng.cam.ac.uk/MoDS MoDS_inputs.xsd" xmlns="http://como.cheng.cam.ac.uk/MoDS" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <algorithms>
        <algorithm name="Data_Algorithm" display_name="Base data for surrogate model">
            <details>
                <detail name="algorithm_type">Read_previous</detail>
                <detail name="optimisable_param_subtypes">subtype_x1 subtype_x2</detail>
                <detail name="response_param_subtypes">subtype_y1 subtype_y2</detail>
                <detail name="param_subtypes">subtype_x1 subtype_x2 subtype_y1 subtype_y2</detail>
                <detail name="output_values">false</detail>
                <detail name="previous_algorithm">Data_Algorithm</detail>
            </details>
        </algorithm>
        <algorithm name="GenSurrogateAlg" display_name="Surrogate model">
            <details>
                <detail name="algorithm_type">Surrogate</detail>
                <detail name="optimisable_param_subtypes">subtype_x1 subtype_x2</detail>
                <detail name="response_param_subtypes">subtype_y1 subtype_y2</detail>
                <detail name="global">false</detail>
                <detail name="surrogate_type">HDMR</detail>
                <detail name="fit_to_coded_responses">false</detail>
                <detail name="order">6</detail>
                <detail name="HDMRorder">2</detail>
                <detail name="r_squared_tol">0.99999</detail>
                <detail name="previous_algorithm">Data_Algorithm</detail>
            </details>
        </algorithm>
    </algorithms>
    <models>
        <model name="Data">
            <details>
                <detail name="model_type">Executable</detail>
            </details>
        </model>
    </models>
    <cases>
        <case name="CaseGroup_Case">
            <models>
                <model>Data</model>
            </models>
        </case>
    </cases>
    <files>
        <file file_name="MODS_SIM_INITFILE__cases.csv">
            <details>
                <detail name="delimiter">,</detail>
                <detail name="file_type">DSV</detail>
            </details>
        </file>
        <file file_name="MODS_SIM_INITFILE__AIVarInitReadFile.csv">
            <details>
                <detail name="delimiter">,</detail>
                <detail name="file_type">DSV</detail>
            </details>
        </file>
    </files>
    <parameters>
        <parameter type="active_input" subtype="subtype_x1" name="x1" preserve_white_space="true">
            <scaling>linear</scaling>
            <cases>
                <case>CaseGroup_Case</case>
            </cases>
            <models>
                <model>Data</model>
            </models>
            <files>
                <initial_read>
                    <details>
                        <detail name="column">x1</detail>
                        <detail name="row">0</detail>
                        <detail name="file_name">MODS_SIM_INITFILE__AIVarInitReadFile.csv</detail>
                        <detail name="read_function">Get_DSV_double</detail>
                        <detail name="lb_abs">1.0</detail>
                        <detail name="ub_abs">3.0</detail>
                    </details>
                </initial_read>
            </files>
        </parameter>
        <parameter type="active_input" subtype="subtype_x2" name="x2" preserve_white_space="true">
            <scaling>linear</scaling>
            <cases>
                <case>CaseGroup_Case</case>
            </cases>
            <models>
                <model>Data</model>
            </models>
            <files>
                <initial_read>
                    <details>
                        <detail name="column">x2</detail>
                        <detail name="row">0</detail>
                        <detail name="file_name">MODS_SIM_INITFILE__AIVarInitReadFile.csv</detail>
                        <detail name="read_function">Get_DSV_double</detail>
                        <detail name="lb_abs">2.0</detail>
                        <detail name="ub_abs">4.0</detail>
                    </details>
                </initial_read>
            </files>
        </parameter>
        <parameter type="active_output" subtype="subtype_y1" case_detail_sep=";" n_params_per_case="1" name="y1" preserve_white_space="true">
            <scaling>linear</scaling>
            <cases>
                <case>CaseGroup_Case</case>
            </cases>
            <models>
                <model>Data</model>
            </models>
            <files>
                <initial_read>
                    <details>
                        <detail name="column">y1</detail>
                        <detail name="row">0</detail>
                        <detail name="file_name">MODS_SIM_INITFILE__cases.csv</detail>
                        <detail name="read_function">Get_DSV_double</detail>
                        <detail name="lb_factor">1.0</detail>
                        <detail name="ub_factor">1.0</detail>
                        <detail name="lb_addend">-1.0</detail>
                        <detail name="ub_addend">1.0</detail>
                    </details>
                </initial_read>
            </files>
        </parameter>
        <parameter type="active_output" subtype="subtype_y2" case_detail_sep=";" n_params_per_case="1" name="y2" preserve_white_space="true">
            <scaling>linear</scaling>
            <cases>
                <case>CaseGroup_Case</case>
            </cases>
            <models>
                <model>Data</model>
            </models>
            <files>
                <initial_read>
                    <details>
                        <detail name="column">y2</detail>
                        <detail name="row">0</detail>
                        <detail name="file_name">MODS_SIM_INITFILE__cases.csv</detail>
                        <detail name="read_function">Get_DSV_double</detail>
                        <detail name="lb_factor">1.0</detail>
                        <detail name="ub_factor">1.0</detail>
                        <detail name="lb_addend">-1.0</detail>
                        <detail name="ub_addend">1.0</detail>
                    </details>
                </initial_read>
            </files>
        </parameter>
    </parameters>
</mods>
